version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6-browsers
    steps:
      - checkout
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar
          background: true
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements/dev.txt --cache-dir=venv
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - ~/project/venv
      - run: venv/bin/pytest tests/test_selenium.py

workflows:
  version: 2
  everything:
    jobs:
      - build
